-- LSP configuration
-- Add language servers as needed:
--   :Mason                          — install servers
--   require("lspconfig").xxx.setup{} — configure per language

-- Auto-format on save (uncomment to enable)
-- vim.api.nvim_create_autocmd("BufWritePre", {
--   callback = function()
--     vim.lsp.buf.format({ async = false })
--   end,
-- })
